[name]
# une chaine de caractere.
project_name = "mon super projet"

[semester]
# un entier positif représentant votre semestre.
semester = 2
# La chaine de caractere "SR" ou "IL" pour votre filière Systemes et Réseaux ou Ingénieurie Logiciel "None" si vous êtes en semestre 1 ou 2.
sector = "SR"

[technologies]
# Une liste de chaine de caracteres des technologies que vous avex utilisé.
technologies = ["C#", "Kotlin", "Javascript"]

[logo]
# L'url publique de votre logo.
url = "https://mon_super_logo.png"

[slogan]
# Une chaine de caractere.
slogan = "the super project"

[pitch]
# Une chaine de caractere.
pitch = "Vous avez des problemes ? Notre super project est là pour vous !"

[team]
# Le chef de projet, "None" si vous n'en avez pas.
leader = "Chef de Projet"
# La liste des membres de votre projet. Ne remettez pas le chef de projet si il est précisé.
members = ["Team member one", "Team member two"]

# Cette table est optionnel, si vous n'avez pas d'autres ressources, supprimez ces lignes
[othersDocuments]
# Des liens directs vers vos autres ressources
urls = ["https://ma_ressource", "http://une_autre_ressource", "https://une_dernière_ressource"]